import { describe, expect, it } from 'vitest'

import { buildChatMarkdown } from './useChatMarkdownExport'
import type { ChatRenderedMessage } from '@/types/chat'

describe('buildChatMarkdown', () => {
  it('exports subagent completion messages as readable summaries, not raw JSON', () => {
    const json = JSON.stringify({
      type: 'subagent_completion',
      parent_session_key: 'agent:main:webchat:wo01onmp',
      child_session_key: 'agent:main:subagent:4dd8059d',
      status: 'succeeded',
      terminal_reason: 'completed',
      result: {
        text: 'OK',
      },
    })

    const markdown = buildChatMarkdown({
      title: '烟火App创意设计',
      exportedAt: '2026-06-29T07:30:02.759Z',
      aiGeneratedLabel: 'Content generated by AI, for reference only.',
      messages: [{
        displayRole: 'subagent',
        roleLabel: 'Sub-agent',
        text: json,
        timeStr: '3m ago',
      } as ChatRenderedMessage],
    })

    expect(markdown).toContain('## Sub-agent')
    expect(markdown).toContain('Subagent agent:main:subagent:4dd8059d completed with status succeeded')
    expect(markdown).toContain('Result:\nOK')
    expect(markdown).not.toContain('"type": "subagent_completion"')
    expect(markdown).not.toContain('"parent_session_key"')
  })

  it('exports protocol-shaped documentation without truncating it', () => {
    const text = [
      'Document `<tool_calls>` inline.',
      '```xml',
      '<tool_calls><invoke name="demo"></invoke></tool_calls>',
      '```',
      'Keep `<｜DSML｜tool_calls>` too.',
      '<details><summary>View areas around line 10</summary>Visible note.</details>',
      'Final suffix.',
    ].join('\n')

    const markdown = buildChatMarkdown({
      title: 'Protocol documentation',
      exportedAt: '2026-07-15T14:39:00.000Z',
      aiGeneratedLabel: 'Content generated by AI, for reference only.',
      messages: [{
        displayRole: 'assistant',
        roleLabel: 'Assistant',
        text,
        timeStr: 'now',
      } as ChatRenderedMessage],
    })

    expect(markdown).toContain(text)
    expect(markdown).toContain('Final suffix.')
    expect(markdown).toContain('> Content generated by AI, for reference only.')
  })
})
